/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsFolkwaysRouteImport } from './routes/projects.folkways'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFolkwaysRoute = ProjectsFolkwaysRouteImport.update({
  id: '/projects/folkways',
  path: '/projects/folkways',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/folkways': typeof ProjectsFolkwaysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/folkways': typeof ProjectsFolkwaysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/folkways': typeof ProjectsFolkwaysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/folkways'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/folkways'
  id: '__root__' | '/' | '/projects/folkways'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsFolkwaysRoute: typeof ProjectsFolkwaysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/folkways': {
      id: '/projects/folkways'
      path: '/projects/folkways'
      fullPath: '/projects/folkways'
      preLoaderRoute: typeof ProjectsFolkwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsFolkwaysRoute: ProjectsFolkwaysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
