/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ProjectsBWayRouteImport } from './routes/projects.b-way'
import { Route as ProjectsElevateLocalRouteImport } from './routes/projects.elevate-local'
import { Route as ProjectsFolkwaysRouteImport } from './routes/projects.folkways'
import { Route as ProjectsPawRoyaltyRouteImport } from './routes/projects.paw-royalty'
import { Route as ProjectsXtendoGlobalRouteImport } from './routes/projects.xtendo-global'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsBWayRoute = ProjectsBWayRouteImport.update({
  id: '/projects/b-way',
  path: '/projects/b-way',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsElevateLocalRoute = ProjectsElevateLocalRouteImport.update({
  id: '/projects/elevate-local',
  path: '/projects/elevate-local',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFolkwaysRoute = ProjectsFolkwaysRouteImport.update({
  id: '/projects/folkways',
  path: '/projects/folkways',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPawRoyaltyRoute = ProjectsPawRoyaltyRouteImport.update({
  id: '/projects/paw-royalty',
  path: '/projects/paw-royalty',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsXtendoGlobalRoute = ProjectsXtendoGlobalRouteImport.update({
  id: '/projects/xtendo-global',
  path: '/projects/xtendo-global',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/projects/b-way': typeof ProjectsBWayRoute
  '/projects/elevate-local': typeof ProjectsElevateLocalRoute
  '/projects/folkways': typeof ProjectsFolkwaysRoute
  '/projects/paw-royalty': typeof ProjectsPawRoyaltyRoute
  '/projects/xtendo-global': typeof ProjectsXtendoGlobalRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/projects/b-way': typeof ProjectsBWayRoute
  '/projects/elevate-local': typeof ProjectsElevateLocalRoute
  '/projects/folkways': typeof ProjectsFolkwaysRoute
  '/projects/paw-royalty': typeof ProjectsPawRoyaltyRoute
  '/projects/xtendo-global': typeof ProjectsXtendoGlobalRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/projects/b-way': typeof ProjectsBWayRoute
  '/projects/elevate-local': typeof ProjectsElevateLocalRoute
  '/projects/folkways': typeof ProjectsFolkwaysRoute
  '/projects/paw-royalty': typeof ProjectsPawRoyaltyRoute
  '/projects/xtendo-global': typeof ProjectsXtendoGlobalRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/projects/b-way'
    | '/projects/elevate-local'
    | '/projects/folkways'
    | '/projects/paw-royalty'
    | '/projects/xtendo-global'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/projects/b-way'
    | '/projects/elevate-local'
    | '/projects/folkways'
    | '/projects/paw-royalty'
    | '/projects/xtendo-global'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/projects/b-way'
    | '/projects/elevate-local'
    | '/projects/folkways'
    | '/projects/paw-royalty'
    | '/projects/xtendo-global'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProjectsBWayRoute: typeof ProjectsBWayRoute
  ProjectsElevateLocalRoute: typeof ProjectsElevateLocalRoute
  ProjectsFolkwaysRoute: typeof ProjectsFolkwaysRoute
  ProjectsPawRoyaltyRoute: typeof ProjectsPawRoyaltyRoute
  ProjectsXtendoGlobalRoute: typeof ProjectsXtendoGlobalRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/b-way': {
      id: '/projects/b-way'
      path: '/projects/b-way'
      fullPath: '/projects/b-way'
      preLoaderRoute: typeof ProjectsBWayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/elevate-local': {
      id: '/projects/elevate-local'
      path: '/projects/elevate-local'
      fullPath: '/projects/elevate-local'
      preLoaderRoute: typeof ProjectsElevateLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/folkways': {
      id: '/projects/folkways'
      path: '/projects/folkways'
      fullPath: '/projects/folkways'
      preLoaderRoute: typeof ProjectsFolkwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/paw-royalty': {
      id: '/projects/paw-royalty'
      path: '/projects/paw-royalty'
      fullPath: '/projects/paw-royalty'
      preLoaderRoute: typeof ProjectsPawRoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/xtendo-global': {
      id: '/projects/xtendo-global'
      path: '/projects/xtendo-global'
      fullPath: '/projects/xtendo-global'
      preLoaderRoute: typeof ProjectsXtendoGlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProjectsBWayRoute: ProjectsBWayRoute,
  ProjectsElevateLocalRoute: ProjectsElevateLocalRoute,
  ProjectsFolkwaysRoute: ProjectsFolkwaysRoute,
  ProjectsPawRoyaltyRoute: ProjectsPawRoyaltyRoute,
  ProjectsXtendoGlobalRoute: ProjectsXtendoGlobalRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
